apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-api
      version: blue
  template:
    metadata:
      labels:
        app: notes-api
        version: blue
    spec:
      containers:
        - name: notes-api
          image: notes-api:v1
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
